### ISSUE TITLE
com.domenicseccareccia.jpegautorotate.JpegAutorotateException: Unable to read JPEG image EXIF Image Width and/or Image Height metadata tags.

### ISSUE THREAD

**Issue by jsheflin** [domsec/jpeg-autorotate#31]
Hi,

With some jpegs, I am seeing this, and not sure of the best way to check for the details.

com.domenicseccareccia.jpegautorotate.JpegAutorotateException: Unable to read JPEG image EXIF Image Width and/or Image Height metadata tags.

thanks

**Comment by domsec** [comment]
Hi,

First, you can first check if the image you are rotating has the appropriate EXIF Image Width/Height metadata tags. You can use http://metapicz.com/#landing to check if such tags are missing from your image. 

Secondly, from a debugging perspective you can look at `updateAllMetadataDimensions()` method in the `JpegImageMetadata` class. 

Rotation will not be possible unless the image file has these two tags.

**Comment by jsheflin** [comment]
Thanks, I appreciate the response.   I should have been more specific, as I'm trying to get the syntax right to check for the appropriate EXIF Image Width/Height metadata tags in an if statement.

**Comment by domsec** [comment]
This library does not provide the ability to extract the EXIF Image Width/Height metadata tags to check appropriateness. It simply just expects an image as input and returns either the rotated image or an error. Extraction and checking is handled for you when determining whether or not it is appropriate to rotate the image.
